Databases week2
rismita87/hyf-homework pull request #15
Opened 2022-03-18 18:22 UTC by rismita87

Databases week2 home work

2022-03-20 15:43 UTC, mateusms01 requested changes
Minor comments added, really well done!

2022-03-20 15:43 UTC, mateusms01 commented on databases/week2/main.sql
> +ALTER TABLE
very well formatted long query. well done

2022-03-20 15:43 UTC, mateusms01 commented on databases/week2/main2.sql
> +  id int PRIMARY KEY,
good use of primary key

2022-03-20 15:43 UTC, mateusms01 commented on databases/week2/main.sql
> +UPDATE
Formatting suggestion, I wouldn't split the UPDATE statement from the TABLE NAME it updates. 

Pointer: improves code readability and clarity

2022-03-20 15:43 UTC, mateusms01 commented on databases/week2/main3.sql
> +  task
formatting tip, would always keep from + table name on the same line. 
Pointer: improves readability and clarity

2022-03-20 15:43 UTC, mateusms01 commented on databases/week2/main3.sql
> +  task
see other occurrences and  update

2022-03-20 15:43 UTC, mateusms01 commented on databases/week2/main4.sql
> +---Part 4: Creating a database
well done here! really well elaborated-

2022-03-20 15:43 UTC, mateusms01 commented on databases/week2/main4.sql
> +  id INT PRIMARY KEY,
well done defining the PK!

2022-03-20 19:27 UTC, rismita87 commented
Hi Mateus,
thanks a lot for your feedback. It would be really helpful if you can give
some feedback on the entity relationship diagram (pdf file) as well.
Thanks & Regards

On Sun, 20 Mar 2022, 16:43 Mateus Souza, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Minor comments added, really well done!
> ------------------------------
>
> In databases/week2/main.sql
> <https://github.com/rismita87/hyf-homework/pull/15#discussion_r830628099>:
>
> > @@ -0,0 +1,62 @@
> +-- Part 1: Working with tasks
> +-- 1.Add a task with these attributes: title, description, created, updated, due_date, status_id, user_id
> +SET
> +  NAMES utf8mb4;
> +USE hyfdbweek2;
> +ALTER TABLE
>
> very well formatted. well done
> ------------------------------
>
> In databases/week2/main2.sql
> <https://github.com/rismita87/hyf-homework/pull/15#discussion_r830628192>:
>
> > @@ -0,0 +1,29 @@
> +---Part 2: School database
> +-- Create a new database containing the following tables:
> +CREATE DATABASE hyfdbweek2HW DEFAULT CHARACTER SET = 'utf8mb4';
> +USE hyfdbweek2HW;
> +-- Class: with the columns: id, name, begins (date), ends (date)
> +CREATE TABLE Class (
> +  id int PRIMARY KEY,
>
> good use of primary key
> ------------------------------
>
> In databases/week2/main.sql
> <https://github.com/rismita87/hyf-homework/pull/15#discussion_r830629499>:
>
> > +    due_date,
> +    status_id,
> +    user_id
> +  )
> +VALUES
> +  (
> +    "Homework",
> +    "Databases week2 homework",
> +    "2022-03-13 06:54:16",
> +    "2022-03-15 06:54:16",
> +    "2022-03-18 06:54:16",
> +    "1",
> +    "rismita87"
> +  );
> +--2.Change the title of a task
> +UPDATE
>
> Formatting suggestion, I wouldn't split the UPDATE statement from the
> TABLE NAME it updates.
>
> Pointer: improves code readability and clarity
> ------------------------------
>
> In databases/week2/main3.sql
> <https://github.com/rismita87/hyf-homework/pull/15#discussion_r830633523>:
>
> > @@ -0,0 +1,53 @@
> +--Part 3: More queries
> +SET
> +  NAMES utf8mb4;
> +USE hyfdbweek2;
> +--1.Get all the tasks assigned to users whose email ends in @spotify.com
> +SELECT
> +  task.title,
> +  user.email
> +FROM
> +  task
>
> formatting tip, would always keep from + table name on the same line.
> Pointer: improves readability and clarity
> ------------------------------
>
> In databases/week2/main4.sql
> <https://github.com/rismita87/hyf-homework/pull/15#discussion_r830634824>:
>
> > @@ -0,0 +1,51 @@
> +---Part 4: Creating a database
>
> well done here! really well elaborated-
> ------------------------------
>
> In databases/week2/main4.sql
> <https://github.com/rismita87/hyf-homework/pull/15#discussion_r830635057>:
>
> > @@ -0,0 +1,51 @@
> +---Part 4: Creating a database
> +CREATE DATABASE dbweek2HW4 DEFAULT CHARACTER SET = 'utf8mb4';
> +USE dbweek2HW4;
> +CREATE TABLE genre(
> +  id INT PRIMARY KEY,
>
> well done defining the PK!
> ------------------------------
>
> In databases/week2/main3.sql
> <https://github.com/rismita87/hyf-homework/pull/15#discussion_r830634549>:
>
> > @@ -0,0 +1,53 @@
> +--Part 3: More queries
> +SET
> +  NAMES utf8mb4;
> +USE hyfdbweek2;
> +--1.Get all the tasks assigned to users whose email ends in @spotify.com
> +SELECT
> +  task.title,
> +  user.email
> +FROM
> +  task
>
> see other occurrences and update
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rismita87/hyf-homework/pull/15#pullrequestreview-915113155>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV6LVNP3ULZ6VNVV3DFWTALVA5BSRANCNFSM5RCSN4ZQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-21 08:23 UTC, mateusms01 commented
Hey Rismita, really sorry for that I completely overlooked the diagram. 

In general the diagram is great, and well defined. However, there is two tables that I don't think are necessary.

Both Genre-Book and Books-Racks are Many-to-One and not Many-to-Many, therefore they could be directly linked without intermediate tables.

2022-03-21 14:30 UTC, rismita87 commented
Hi Mateus, thanks for your feedback.
Regards
Rismita.

On Mon, 21 Mar 2022 at 09.23, Mateus Souza ***@***.***> wrote:

> Hey Rismita, really sorry for that I completely overlooked the diagram.
>
> In general the diagram is great, and well defined. However, there is two
> tables that I don't think are necessary.
>
> Both Genre-Book and Books-Racks are Many-to-One and not Many-to-Many,
> therefore they could be directly linked without intermediate tables.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rismita87/hyf-homework/pull/15#issuecomment-1073610075>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV6LVNKFLCGJDPGLS3AGNXLVBAWYBANCNFSM5RCSN4ZQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-17 19:40 UTC, merged